steps:
 # Build and push steps remain the same
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/tutti-learni-repo/tutti-learni-api:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/tutti-learni-repo/tutti-learni-api:$SHORT_SHA']

  # Deploy the container image to Cloud Run
  - name: 'google/cloud-sdk:latest'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tutti-learni-api'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/tutti-learni-repo/tutti-learni-api:$SHORT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=ConnectionStrings__DefaultConnection="Host=/cloudsql/tuttilearni-54f1f:europe-west1:tutti-learni-db;Database=tutti-learni-db;Username=postgres;Password=Tl&Dk/G6shlB0{*g"'
      - '--add-cloudsql-instances=tuttilearni-54f1f:europe-west1:tutti-learni-db'
      - '--startup-probe=httpGet.path=/swagger/v1/swagger.json,initialDelaySeconds=240'
      - '--command=sleep'
      - '--args=3600'

# Store the image in your Artifact Registry
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/tutti-learni-repo/tutti-learni-api:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
